### PR TITLE
hu (Hungarian - magyar) locale

### PR DESCRIPTION
**Pull request by ovari**
Please advise when you have merge the hu locale so we can delete our fork. Thank you

### CODE REVIEW

**Comment by ovari** [comment]
Please advise when you have merged this so we can delete our fork. Thank you

**Comment by ovari** [comment]
Thank you @tipichris for merging.

**Comment by ovari** [comment]
@tipichris can you please add the `hu` locale to https://www.oak-wood.co.uk/downloads/tbdialout/tbdialout-2.0.0pre1.xpi? Thank you

**Comment by tipichris** [comment]
2.0.0 has been submitted to ATN with Hungarian included.
I have also submitted 1.8.1 - a version compatible with TB68 and identical to the previous 1.8.0 except for the addition of your translation.
Pending review on ATN both can be downloaded from https://www.oak-wood.co.uk/downloads/tbdialout/

**Comment by ovari** [comment]
Will you be adding `hu` to the `About this Add-on` section on [ATN](https://addons.thunderbird.net/thunderbird/addon/tbdialout/)?
> TBDialOut currently has translations for en-US, en-GB, de, es-ES, nl, fr, zh-CN, sv-SE, ru and it. If you fancy translating it into another language, visit TBDialOut at Babelzilla http://bit.ly/tbdialout-l10n.

Perhaps the list of locales could be in alphabetical order? What do you think?

Thank you

**Pull request merged**
